	.align 2
voicegroup601::
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 0 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 1 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 2 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 3 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 4 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 5 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 6 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 7 | Square-1 | --
	voice_directsound 60, 0, DirectSoundWaveData_GoldenSun2InstrumentSample001, 255, 0, 255, 165              @ 8 | Direct |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 9 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 10 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 11 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 12 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 13 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 14 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 15 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 16 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 17 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 18 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 19 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 20 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 21 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 22 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 23 | Square-1 | --
	voice_directsound 60, 0, DirectSoundWaveData_GoldenSun2InstrumentSample002, 255, 0, 255, 165              @ 24 | Direct |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 25 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 26 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 27 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 28 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 29 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 30 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 31 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 32 | Square-1 | --
	voice_directsound 60, 0, DirectSoundWaveData_GoldenSun2InstrumentSample003, 255, 0, 255, 165              @ 33 | Direct |
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_GoldenSun2pcm001, 0, 2, 3, 3                      @ 34 | Wave |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 35 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 36 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 37 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 38 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 39 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 40 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 41 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 42 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 43 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 44 | Square-1 | --
	voice_directsound 60, 0, DirectSoundWaveData_GoldenSun2InstrumentSample004, 255, 0, 255, 165              @ 45 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_GoldenSun2InstrumentSample005, 255, 0, 255, 165              @ 46 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_GoldenSun2InstrumentSample006, 255, 0, 255, 165              @ 47 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_GoldenSun2InstrumentSample007, 255, 0, 255, 165              @ 48 | Direct |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 49 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 50 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 51 | Square-1 | --
	voice_directsound 60, 0, DirectSoundWaveData_GoldenSun2InstrumentSample008, 255, 0, 255, 165              @ 52 | Direct |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 53 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 54 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 55 | Square-1 | --
	voice_directsound 60, 0, DirectSoundWaveData_GoldenSun2InstrumentSample009, 255, 0, 255, 165              @ 56 | Direct |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 57 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 58 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 59 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 60 | Square-1 | --
	voice_directsound 60, 0, DirectSoundWaveData_GoldenSun2InstrumentSample010, 255, 0, 255, 165              @ 61 | Direct |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 62 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 63 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 64 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 65 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 66 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 67 | Square-1 | --
	voice_directsound 60, 0, DirectSoundWaveData_GoldenSun2InstrumentSample011, 255, 0, 255, 165              @ 68 | Direct |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 69 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 70 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 71 | Square-1 | --
	voice_directsound 60, 0, DirectSoundWaveData_GoldenSun2InstrumentSample012, 255, 0, 255, 165              @ 72 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_GoldenSun2InstrumentSample013, 255, 0, 255, 165              @ 73 | Direct |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 74 | Square-1 | --
	voice_directsound 60, 0, DirectSoundWaveData_GoldenSun2InstrumentSample014, 255, 0, 255, 165              @ 75 | Direct |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 76 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 77 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 78 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 79 | Square-1 | --
	voice_directsound 60, 0, DirectSoundWaveData_GoldenSun2InstrumentSample015, 85, 165, 193, 178             @ 80 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_GoldenSun2InstrumentSample016, 85, 165, 193, 178             @ 81 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_GoldenSun2InstrumentSample017, 85, 165, 193, 178             @ 82 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_GoldenSun2InstrumentSample018, 85, 165, 167, 178             @ 83 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_GoldenSun2InstrumentSample019, 85, 127, 218, 165             @ 84 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_GoldenSun2InstrumentSample015, 22, 165, 193, 195             @ 85 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_GoldenSun2InstrumentSample016, 22, 165, 193, 195             @ 86 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_GoldenSun2InstrumentSample017, 22, 165, 193, 195             @ 87 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_GoldenSun2InstrumentSample018, 22, 165, 167, 195             @ 88 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_GoldenSun2InstrumentSample019, 22, 127, 218, 165             @ 89 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_GoldenSun2InstrumentSample015, 255, 235, 90, 178             @ 90 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_GoldenSun2InstrumentSample016, 255, 235, 90, 178             @ 91 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_GoldenSun2InstrumentSample017, 255, 235, 90, 178             @ 92 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_GoldenSun2InstrumentSample018, 255, 235, 103, 178            @ 93 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_GoldenSun2InstrumentSample019, 255, 235, 103, 165            @ 94 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_GoldenSun2InstrumentSample015, 255, 127, 90, 165             @ 95 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_GoldenSun2InstrumentSample015, 255, 127, 90, 165             @ 96 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_GoldenSun2InstrumentSample017, 255, 127, 90, 165             @ 97 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_GoldenSun2InstrumentSample018, 255, 127, 90, 165             @ 98 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_GoldenSun2InstrumentSample019, 255, 127, 103, 165            @ 99 | Direct |
	voice_square_1_alt 60, 0, 0, 3, 0, 1, 7, 0                                                                @ 100 | Square-1 |
	voice_square_2_alt 60, 0, 3, 0, 1, 7, 0                                                                   @ 101 | Square-2 |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 102 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 103 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 104 | Square-1 | --
	voice_directsound 60, 0, DirectSoundWaveData_GoldenSun2InstrumentSample021, 255, 235, 103, 178            @ 105 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_GoldenSun2InstrumentSample022, 255, 242, 103, 178            @ 106 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_GoldenSun2InstrumentSample023, 255, 0, 255, 165              @ 107 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_GoldenSun2InstrumentSample024, 255, 0, 255, 165              @ 108 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_GoldenSun2InstrumentSample025, 255, 0, 255, 165              @ 109 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_GoldenSun2InstrumentSample026, 255, 235, 103, 178            @ 110 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_GoldenSun2InstrumentSample027, 255, 0, 255, 165              @ 111 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_GoldenSun2InstrumentSample028, 255, 0, 255, 165              @ 112 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_GoldenSun2InstrumentSample029, 255, 0, 255, 165              @ 113 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_GoldenSun2InstrumentSample030, 255, 235, 103, 178            @ 114 | Direct |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 115 | Square-1 | --
	voice_directsound 80, 0, DirectSoundWaveData_GoldenSun2InstrumentSample031, 255, 0, 255, 0                @ 116 | Direct |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 117 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 118 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 119 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 120 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 121 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 122 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 123 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 124 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 125 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 126 | Square-1 | --
	voice_keysplit_all voicegroup602                                                                          @ 127 | Drum |

